name: Update Homebrew Formula

on:
  workflow_dispatch:
  pull_request:

jobs:
  update-formula:
    runs-on: ubuntu-latest
    container:
      image: homebrew/brew:latest
      options: --user root
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Update CLI Version
        run: |
          make update-cli-version
